### ISSUE TITLE
Improve serialization speed

### ISSUE THREAD

**Issue by trojczak** [edmcouncil/rdf-toolkit#34] opened 2022-10-14 07:57 UTC
For longer ontologies, it takes too long to process. We need to improve this.

**Comment by ajnelson-nist** [comment] 2022-10-27 19:41
I've noticed there is a significant slowdown corresponding with the length of `rdf:List`s.  Is code handling sorting `rdf:List`s in this code base, or in an imported library?

**Comment by ajnelson-nist** [comment] 2022-10-27 19:41
Addendum: I observe this most often with Turtle serialization.

**Comment by mereolog** [comment] 2022-10-28 07:07
@ajnelson-nist did you try [the latest build](https://jenkins.edmcouncil.org/view/rdf-toolkit/job/rdf-toolkit-build/lastSuccessfulBuild/artifact/target/rdf-toolkit.jar):  ?
I am asking because the speed should be improved by https://github.com/edmcouncil/rdf-toolkit/pull/35.

If it is still bad in your opinion, could you send us a file to test together with some estimate of time needed for its serialisation?

**Comment by ajnelson-nist** [comment] 2022-11-15 22:15
Hi @mereolog ,

Apologies for the delayed reply.

The file with which I've seen a `rdf:List`-based slowdown most frequently is this one:

https://github.com/ucoProject/UCO/blob/master/ontology/uco/vocabulary/vocabulary.ttl

Sorting that should take under 1 second.  However, because of something involving how `rdf-toolkit` sorts `rdf:List` members, the runtime is superlinear w.r.t. length of at least the longest `rdf:List`.

For example, after observing the runtime of that file as-is, try removing any hunk of the list involved with `vocabulary:ObservableObjectRelationshipVocab`.  You should see the time decrease dramatically.

I think the issue is `rdf-toolkit` is not treating a `rdf:List` as an item that only needs its head sorted with wherever the head is referenced.  There should be no decision process involved with any member of the list after the first `rdf:next`, once the `rdf:List` is constructed.  For example, a file with two 100-member `rdf:List`s defined, and nothing else, should only sort 2 nodes, not 200.

FWIW, I did see a speedup from the build posted soon after #35 was merged.  However, the fundamental issue still remains.

**Comment by mereolog** [comment] 2023-05-26 09:55
> Hi @mereolog ,
> 
> Apologies for the delayed reply.
> 
> The file with which I've seen a `rdf:List`-based slowdown most frequently is this one:
> 
> https://github.com/ucoProject/UCO/blob/master/ontology/uco/vocabulary/vocabulary.ttl
> 
> Sorting that should take under 1 second. However, because of something involving how `rdf-toolkit` sorts `rdf:List` members, the runtime is superlinear w.r.t. length of at least the longest `rdf:List`.
> 
> For example, after observing the runtime of that file as-is, try removing any hunk of the list involved with `vocabulary:ObservableObjectRelationshipVocab`. You should see the time decrease dramatically.
> 
> I think the issue is `rdf-toolkit` is not treating a `rdf:List` as an item that only needs its head sorted with wherever the head is referenced. There should be no decision process involved with any member of the list after the first `rdf:next`, once the `rdf:List` is constructed. For example, a file with two 100-member `rdf:List`s defined, and nothing else, should only sort 2 nodes, not 200.
> 
> FWIW, I did see a speedup from the build posted soon after #35 was merged. However, the fundamental issue still remains.

Suppose there are two lists:
1. [A, B, C]
2. [A, D, E]
When serialising a graph with these two lists, the serialiser may need to sort the lists themselves, i.e., it needs to establish which list is put first in the sorted file. The current solution is that the serialiser walks both lists and compare its elements as long as it finds different elements. Then it finds which of the different elements is to be sorted first and this element decides which list is sorted first. 
In the example below list 1 is sorted before 2 because its second element is sorted before the second element of list 2 - I assume a simple lexicographic sorting for elements.

The time needed for this operation should be linear wrt length of the list being sorted.

**Closed** 2023-06-09 06:41 UTC
